#ifndef TASKS_COMMON_H_
#define TASKS_COMMON_H_

// WiFi application task
#define WIFI_APP_TASK_STACK_SIZE 4096
#define WIFI_APP_TASK_PRIORITY   5
#define WIFI_APP_TASK_CORE_ID    0

// HTTP server task
#define HTTP_SERVER_TASK_STACK_SIZE 8192
#define HTTP_SERVER_TASK_PRIORITY   4
#define HTTP_SERVER_TASK_CORE_ID    0

// HTTP server monitor task
#define HTTP_SERVER_MONITOR_STACK_SIZE 4096
#define HTTP_SERVER_MONITOR_PRIORITY   3
#define HTTP_SERVER_MONITOR_CORE_ID    0

// AHT20 Sensor task
#define AHT20_TASK_STACK_SIZE 4096
#define AHT20_TASK_PRIORITY   5
#define AHT20_TASK_CORE_ID    1

// Soil Moisture Sensor
#define MOISTURE_SENSOR_TASK_STACK_SIZE 4096
#define MOISTURE_SENSOR_TASK_PRIORITY   4
#define MOISTURE_SENSOR_TASK_CORE_ID    1

// Sleep toggle button
#define SLEEP_TOGGLE_BUTTON_TASK_STACK_SIZE 2048
#define SLEEP_TOGGLE_BUTTON_TASK_PRIORITY   6
#define SLEEP_TOGGLE_BUTTON_TASK_CORE_ID    0

// SNTP Time sync task
#define SNTP_TIME_SYNC_TASK_STACK_SIZE 4096
#define SNTP_TIME_SYNC_TASK_PRIORITY   4
#define SNTP_TIME_SYNC_TASK_CORE_ID    1

// AWS IOT task
#define AWS_IOT_TASK_STACK_SIZE 9216
#define AWS_IOT_TASK_PRIORITY   6
#define AWS_IOT_TASK_CORE_ID    1

#endif